export const GET_PRODUCTOS = 'GET_PRODUCTOS';
export const TYPE_DIETA = 'TYPE_DIETA';
export const FILTRO_POR_ORDEN_ALFABETICO = 'FILTRO_POR_ORDEN_ALFABETICO';
export const FILTRO_POR_ORDEN_SCORE = 'FILTRO_POR_ORDEN_SCORE';
export const FILTRO_POR_ORDEN_DIETA = 'FILTRO_POR_ORDEN_DIETA';
export const FILTRO_POR_INPUT = 'FILTRO_POR_INPUT';
export const FILTER_BY_SEARCHBAR ='FILTER_BY_SEARCHBAR';
export const POST_RECIPES = 'POST_RECIPES';